### PR TITLE
Fixed requested by David (multiplicity distributions now filled in on…

### PR DESCRIPTION
**Pull request by atimmins**
…line mode, and vertex range rescaled

### CODE REVIEW

**Comment by davidrohr** [comment]
Hi Ant,
I just tried you patch, but when I apply it, all the TPC QA histograms are no longer filled.
Could you have a look again?
Cheers
David

**Comment by atimmins** [comment]
Hi David,

Can you try without my patch? I think this is an issue due to a previous commit by Mikolaj (which implemented some changes by Ruben in master). 

Cheers,
Ant

**Comment by davidrohr** [comment]
Hi,
When I revert only your patch, the histograms are there as before. I actually tried twice both versions to be sure.
Looking at the code briefly I do not understand it.
But it is definitely related to your patch.
Cheers
David

**Comment by atimmins** [comment]
Hi David,

OK, this is something my end then. Will try to fix.

Cheers,
Ant

**Comment by davidrohr** [comment]
Did you try with an hlt emulation chain in recwar-local.C
Does it fill the histograms there?
If you do not find the problem, I can apply your patch step by step and find the offending change.
It is not that big a patch after all.

**Comment by atimmins** [comment]
Hey, locally, histograms are filled when running the emulator, but not filled when I run on offline ESDs. Strange.

**Comment by mkrzewic** [comment]
i had a look at the benchmark output at GSI - the offline QA for TPC is empty there as well - that was obviously done without Ant's patch

**Comment by davidrohr** [comment]
That is pretty weird, I switched forth and back three times for pp and Pb-Pb data replay to be absolutely sure. With Ant's patch, histograms were empty. Without, they were full.
I'd be surprised if that was coincidence, but perhaps there is some undefined behaviour that does not fill the histograms every time?

**Comment by mkrzewic** [comment]
well, there is a difference in setting up the tasks in online and offline, plus possibly other differences. i'm trying to reproduce it in a controlled (offline) env...

**Comment by davidrohr** [comment]
Ah, actually Ant mentioned yesterday himself that it does not work in the offline setup.

So, with the new software, histograms work online without Ant's patch, they fail online with the patch, and they fail offline in general it seems.

**Comment by atimmins** [comment]
Hi all, let me switch back to the commit (locally) prior to this patch. If I remember correctly, the offline histograms were not filled then, but will confirm

**Comment by atimmins** [comment]
Hi all,

If I switch to the commit before my patch locally:

commit 8fd78745a12123b9e2ddf9ecf76789f20a288fa8
Author: mkrzewic <mikolaj.krzewicki@cern.ch>
Date:   Tue May 9 14:44:18 2017 +0200

    Fix compilation after rebase on alisw/master

The offline histograms are still not filled, while the online histograms are filled. Strange.

Cheers,
Ant

**Comment by mkrzewic** [comment]
the histograms are filled again. At least in offline mode. Testing can commence...

**Comment by atimmins** [comment]
Hi @mkrzewic, implementing the latest commits in dev with this patch, the histograms are now being filled offline and online. I would say it OK to approve the patch.

**Comment by davidrohr** [comment]
I'll deploy on the farm and test when I find time (probably in 2 weeks). I'll leave it to Mikolaj if we want to merge this beforehand.

**Pull request merged**
